Repository Statutis/frontend, pull requests merged in 2022-05, with the labels that each got.

#81 Ajout update services
  src/api/ServiceRepository.ts
  src/components/NavTop.tsx
  src/components/ServiceCard.tsx
  src/main.tsx
  src/pages/Group/GroupOverview.tsx
  src/pages/Register.tsx
  src/pages/Service/ServiceAddAtlassianStatusPage.tsx
Labels: documentation, enhancement

#82 Suppression de référence vers page A propos
  src/components/Footer.tsx
  src/components/NavTop.tsx
Labels: design

#83 Texte dans footer
  src/assets/app/app.scss
  src/components/Footer.tsx
Labels: bug, design
