Repository Statutis/frontend, pull requests merged in 2022-04, with the labels that each got.

#9 8 page de recherche des groupes de services
  .gitignore
  src/Utils/IdGenerator.js
  src/assets/_ui.scss
  src/assets/_vars.scss
  src/assets/ui/_form.scss
  src/assets/ui/_switch.scss
  src/components/UI/Input/Input.jsx
  src/components/UI/Input/Select.jsx
  src/components/UI/Input/Switch.jsx
  src/main.jsx
  src/pages/Search.jsx
  src/pages/UI.jsx
Labels: design

#32 Page d'erreur 404
  src/assets/app/pages/error.scss
  src/components/AppBase.jsx
  src/components/RouteBase.jsx
  src/main.jsx
  src/pages/Error.jsx
Labels: design

#35 Page login
  src/assets/app/pages/login.scss
  src/components/NavTop.jsx
  src/main.jsx
  src/pages/Login.jsx
Labels: design

#39 EsLint + Env + Bouton selecteur page accueil
  .env
  .eslintrc.js
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  package.json
  src/AppContext.js
  src/AppProvider.jsx
  src/api/Models/Group.js
  src/components/AppBase.jsx
  src/components/Footer.jsx
  src/components/GroupServiceCard.jsx
  src/components/NavTop.jsx
  src/components/ProgressBar.jsx
  src/components/RouteBase.jsx
  src/components/SearchServiceBar.jsx
  src/components/UI/Input/Input.jsx
  src/components/UI/Input/Select.jsx
  src/components/UI/Input/Switch.jsx
  src/main.jsx
  src/pages/Error.jsx
  src/pages/Index.jsx
  src/pages/Login.jsx
  src/pages/Search.jsx
  src/pages/UI.jsx
  vite.config.js
  yarn.lock
Labels: bug, enhancement

#40 Docker github action dépendance + Axios + GET des types de services et des équipes
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  package.json
  src/api/Models/Service/ServiceType.js
  src/api/Models/Team.js
  src/api/ServiceTypesRepository.js
  src/api/TeamRepository.js
  src/assets/_ui.scss
  src/assets/ui/_form.scss
  src/assets/ui/_select.scss
  src/components/SearchServiceBar.jsx
  src/components/UI/Input/Select.jsx
  src/main.jsx
  src/pages/Index.jsx
  src/pages/Search.jsx
  src/pages/UI.jsx
  yarn.lock
Labels: enhancement

#49 Orthographe
  src/components/Footer.tsx
  src/components/NavTop.tsx
  src/pages/Index.tsx
  src/pages/Login.tsx
Labels: bug

#57 expiration du token non pris en compte
  src/AppProvider.tsx
  src/Services/AuthService.ts
  src/assets/app/navtop.scss
  src/components/NavTop.tsx
  src/components/UI/ImageLoader.tsx
  src/img/user_avatar.png
  src/main.tsx
  src/pages/Login.tsx
Labels: bug, enhancement

#63 Page de profil
  src/AppProvider.tsx
  src/ProtectedPath.tsx
  src/Services/UserService.ts
  src/Store/AuthSlice.ts
  src/Store/store.ts
  src/api/Models/User.ts
  src/api/TeamRepository.ts
  src/api/UserRepository.ts
  src/assets/app/navtop.scss
  src/assets/app/pages/profil.scss
  src/assets/ui/_badge.scss
  src/assets/ui/_btn.scss
  src/components/NavTop.tsx
  src/components/Profil/ChangePassword.tsx
  src/components/Profil/ChangePersonalData.tsx
  src/components/UI/ImageLoader.tsx
  src/components/UserAvatar.tsx
  src/main.tsx
  src/pages/Profil.tsx
  src/pages/Register.tsx
Labels: enhancement, design

#72 Feature/team
  src/api/AuthRepository.ts
  src/api/Models/Team.ts
  src/api/TeamRepository.ts
  src/api/UserRepository.ts
  src/assets/app/pages/Team/details.scss
  src/assets/app/pages/Team/list.scss
  src/components/Footer.tsx
  src/components/UI/Input/MultipleSelect.tsx
  src/main.tsx
  src/pages/Register.tsx
  src/pages/Team/TeamDelete.tsx
  src/pages/Team/TeamDetails.tsx
  src/pages/Team/TeamForm.tsx
  src/pages/Team/TeamList.tsx
Labels: enhancement, design

#75 ajout form création http service
  src/api/Models/Service/HttpService.ts
  src/api/ServiceRepository.ts
  src/main.tsx
  src/pages/Service/ServiceAddHttp.tsx
  src/pages/Service/ServiceAddPing.tsx
Labels: enhancement

#76 Information sur le status du service
  src/assets/ui/custom/_service_card.scss
  src/components/ServiceCard.tsx
Labels: enhancement, design
